### ISSUE TITLE
Change case configuration files to a more "config-like" format

### ISSUE THREAD

**Issue by mjaehn** [C2SM/processing-chain#22]
The `config.py` file should be replaced by `config.yaml`.

**Comment by efmkoene** [comment]
What I like about the `config.py` format, is that we can have Python expressions within the configuration (i.e., setting one variable can affect other variables; or letting variables be set by reading properties of external files). I'm personally not the biggest fan of moving to `yaml` files and losing that option.

**Comment by mjaehn** [comment]
Issue can be closed once the `icon-art-global-test` case is running.
